import { configureStore } from "@reduxjs/toolkit";

const INIT_STATE = {
  isConnected: false,
  providerType: "",
  walletModal: false,
  balance: 0,
  nftStatisticsData: {
    "0x0D464bDde2301C30871bB4C29bB7DD935f5a985C": {
      name: "Spaceman",
      address: "0x0D464bDde2301C30871bB4C29bB7DD935f5a985C",
      accountPhotoSrc: "../images/accountImg.png",
      nftCollected: 185,
      points: 440,
      achievements: 4,
      items: "12,203",
      tottalPoints: 1080,
      nfts: [
        {
          id: 0,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 1,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 2,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 3,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 4,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 5,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 6,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 7,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
      ],
    },
    "0x0D464bDde2301C30871bB4C29bB7DD935f5a985B": {
      name: "Spaceman",
      address: "0x0D464bDde2301C30871bB4C29bB7DD935f5a985C",
      accountPhotoSrc: "../images/accountImg.png",
      nftCollected: 185,
      points: 440,
      achievements: 4,
      items: "12,203",
      tottalPoints: 1080,
      nfts: [
        {
          id: 0,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 1,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 2,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 3,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 4,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 5,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 6,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 7,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 8,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 9,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        }
      ],
    },
    "0x0D464bDde2301C30871bB4C29bB7DD935f5a985D": {
      name: "Spaceman",
      address: "0x0D464bDde2301C30871bB4C29bB7DD935f5a985C",
      accountPhotoSrc: "../images/accountImg.png",
      nftCollected: 185,
      points: 440,
      achievements: 4,
      items: "12,203",
      tottalPoints: 1080,
      nfts: [
        {
          id: 0,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 1,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 2,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 3,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 4,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 5,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 6,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 7,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 8,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 9,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        }
      ],
    },
    "0x0D464bDde2301C30871bB4C29bB7DD935f5a985E": {
      name: "Spaceman",
      address: "0x0D464bDde2301C30871bB4C29bB7DD935f5a985C",
      accountPhotoSrc: "../images/accountImg.png",
      nftCollected: 185,
      points: 440,
      achievements: 4,
      items: "12,203",
      tottalPoints: 1080,
      nfts: [
        {
          id: 0,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 1,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 2,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 3,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 4,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 5,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 6,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 7,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 8,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        },
        {
          id: 9,
          imgSrc: "../images/nft/arrivals/fig1.png",
          title: "Alfa Kongs Club - AKC",
          subTitle: "Alpha Kong #8223",
          value: "CMCX",
          price: "10.24",
          priceUSD: "$10,314",
        }
      ],
    },
  },
  votingData: {
    "QmbtMK57ksC7DEeqkqKSx7ehFg1ahYMCtiAAAiGaYjVbw4": {
      id: 0,
      title: "Stop Minting more CORE",
      date: "Ends Mar 6th, 2022 11:15",
      location: "Community",
      activeStatus: true,
    },
    "QmbtMK57ksC7DEeqkqKSx7ehFg1ahYMCtiAAAiGaYjVbw4": {
      id: 1,
      title: "Stop Minting more CORE",
      date: "Ends Mar 6th, 2022 11:15",
      location: "Core",
      activeStatus: true,
    },
    "QmbtMK57ksC7DEeqkqKSx7ehFg1ahYMCtiAAAiGaYjVbw4": {
      id: 2,
      title: "Stop Minting more CORE",
      date: "Ends Mar 6th, 2022 11:15",
      location: "Community",
      activeStatus: false,
    },
    "QmbtMK57ksC7DEeqkqKSx7ehFg1ahYMCtiAAAiGaYjVbw4": {
      id: 3,
      title: "Stop Minting more CORE",
      date: "Ends Mar 6th, 2022 11:15",
      location: "Core",
      activeStatus: false,
    },
    "QmbtMK57ksC7DEeqkqKSx7ehFg1ahYMCtiAAAiGaYjVbw4": {
      id: 4,
      title: "Stop Minting more CORE",
      date: "Ends Mar 6th, 2022 11:15",
      location: "Community",
      activeStatus: true,
    },
  },
};

const connectReducer = (state = INIT_STATE, action) => {
  if (action.type === "CONNECT") {
    return {
      isConnected: action.payload.connected,
      providerType: action.payload.type,
    };
  }

  if (action.type === "DISCONNECT") {
    return {
      isConnected: false,
      providerType: "",
    };
  }

  if (action.type === "TOGGLE_WALLET_CONNECT_MODAL") {
    return {
      walletModal: action.payload.walletModal,
    };
  }

  if (action.type === "GET_BALANCE") {
    return {
      balance: action.payload.balance,
    };
  }

  return state;
};

const store = configureStore({
  reducer: connectReducer
});

export default store;
