import Activity from "../../../components/nfts/Activity";

let nftActivityData = [
  {
      id: 0,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Listed',
      priceInCmcx: '0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 1,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Sold',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 2,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Delisted',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 3,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Modified',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 4,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Collection',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 5,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Listed',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 6,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Modified',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 7,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Sold',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 12312323,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Listed',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
      id: 13232,
      itemImg: '/images/nft/nft_activity_items/item1.png',
      itemTitle: 'Alpha Kong #8223',
      itemSubTitle: 'Alpha Kongs Club - AKC',
      event: 'Sold',
      priceInCmcx: 'CMCX 0.0123',
      priceInDollar: '(~$51.028)',
      fromImg: '/images/nft/nft_activity_items/sub_item1.png',
      from: 'BilanCh',
      fromAddress: '0xC7...061b',
      toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
      toReciver: '-',
      toReciverAddress: '0xF5...301c',
      dateDay: '4.7.2022',
      dateTime: '6:28 PM',
      lowestPrice: '0.198',
      hightestPrice: '10,000',
      items: '895',
      supply: '7777'
  },
  {
    id: 22222,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Delisted',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 3555,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Modified',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 411,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Collection',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 51,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Listed',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 6343,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Modified',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 72,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Sold',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 999,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Listed',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 15,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Sold',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 21,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Delisted',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 13,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Modified',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 4343,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Collection',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 5551,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Listed',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 61,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Modified',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  },
  {
    id: 71,
    itemImg: '/images/nft/nft_activity_items/item1.png',
    itemTitle: 'Alpha Kong #8223',
    itemSubTitle: 'Alpha Kongs Club - AKC',
    event: 'Sold',
    priceInCmcx: 'CMCX 0.0123',
    priceInDollar: '(~$51.028)',
    fromImg: '/images/nft/nft_activity_items/sub_item1.png',
    from: 'BilanCh',
    fromAddress: '0xC7...061b',
    toReciverImg: '/images/nft/nft_activity_items/sub_item2.png',
    toReciver: '-',
    toReciverAddress: '0xF5...301c',
    dateDay: '4.7.2022',
    dateTime: '6:28 PM',
    lowestPrice: '0.198',
    hightestPrice: '10,000',
    items: '895',
    supply: '7777'
  }
];

const ActivityPage = (props) => { 
  return <Activity { ...props } />; 
}

export async function getStaticProps() {
  return {
    props: {
      activityData: nftActivityData.slice(0, 20)
    }
  }
}

export default ActivityPage;
